droplet-editor/droplet

- src/controller.coffee
ace editor was not being set to ace/mode/javascript when droplet was initialized in javascript mode.
please verify that this works properly in mode/coffee as I don't have a good way to verify for sure.
also, I don't know if this will also handle dynamic calls to droplet's setMode.
> don't always set ace/mode/coffee

- src/coffee.coffee
- src/javascript.coffee
- test/coffee/parserTests.coffee
- test/coffee/tests.coffee
Dotted methods can now be listed in function whitelists; if a fully-qualified function name such as "Math.round" matches a dotted name, the function name is treated as a single (non-editable) block.
> Add support for dotted methods in Javascript and Coffeescript

- src/coffee.coffee
- test/coffee/tests.coffee
This change (requested by CS First instructors)
avoids treating inline lambda (->) functions as
separate blocks in Coffeescript in two cases:
(1) direct assignment of a lambda
assignable = (x) -> dosomething
Instead of treating the = and the -> as separate blocks, these are
treated as a single block.
(2) use of a lambda as the last argument of a function call
button 'clickme', ->
dosomething
Instead of treating the function call (button(..)) as a separate
block from the ->, these are treated as a single block.
This is implemented by factoring the handling of a -> code block
into an @addCode method, and separating the socket handling from
the delineation of the block for the ->.  @addCode is called
by the Assign handler when the RHS is a Code node and by the
Call handler with the last arg …
> Coffeescript: merge inline code definition blocks.

- src/javascript.coffee
- test/coffee/tests.coffee
This change adds support for (value-colored) blocks that come from
Javascript UnaryExpressions such as ~() and !().  Previously these
nodes were unhandled, so would just be greated as unblockified
plain text areas.
> Support UnaryExpression nodes like !() in Javascript.

- src/javascript.coffee
Previously "return __" could not be parsed as part of the palette
because a top-level return is not allowed in the ECMAScript 5 spec.
It's a slightly odd rule because it adds context-dependence.
While most JS code looks the same everywhere, top-level code actually
has slightly different syntax - because return is not alllowed.
It's easier for the block editor to avoid this asymmetry and allow
return everywhere, at least from the point of view of parsing
blocks.  It turns out this is an issue that has been seen by other
tools, and that acorn has an option that lets us break this rule.
This change sets the allowReturnOutsideFunction option for acorn.
> Allow return ouside function in JS.

- css/droplet.css
- src/controller.coffee
Some of the layers (cursor, highlight, lasso) were too wide, because of the gutter; reduce their width to fit inside the wrapper div.
> Resize canvases properly

- src/controller.coffee
When the palette is resized (after changing the palette header),
the palette highlight canvas should also be resized, so the
highlight outlines are positioned correctly.
Also, if the palette header has only a single group and it
has no name, then the palette header is formatted so that
the palette header is not visible.
> Fix palette highlight position and empty header.

- src/coffee.coffee
- src/controller.coffee
- src/javascript.coffee
- src/model.coffee
- src/parser.coffee
- test/coffee/parserTests.coffee
- test/coffee/tests.coffee
- test/jstest.html
When a Javascript block is empty but surrounded by curly braces, it should be serialized with nothing between the curly braces.  This is different from coffeescript, which needs something inside the indented code.
This change adds support for allowing a language adapter to support "empty indents".
> Support empty indents in Javascript

- Gruntfile.coffee
- README.md
- src/controller.coffee
- test/uitest.html
This feature allows a palette block to "expand" into another block when
dragging out of the palette.  The idea is that the block rendered in
the palette can be an abbreviation, and the "real" block might be bigger,
for example, it might include longer arguments etc.
To configure an expansion block, do the following in the palette configuration:
```js
palette: [{
name: 'Draw',
color: 'blue',
blocks: [{
block: 'pen()',       // this is what you see in the palette
expansion: 'pen red', // this is what you get when you drag
title: 'ptest'
}],
```
This commit also adds a basic uitest that simulates mouse events
to test the controller, which exercises the expansion feature.
> Add expansion blocks to palette

- example/example.coffee
- example/example.html
- src/controller.coffee
This supports a simple `editor.[add|remove|toggle]GutterDecoration(lineNumber, cssClass)`.
It also supports an `editor.on('guttermousedown', function(e) { console.log(e.line); });`
Not yet done: shifting gutter decorations around when line numbers change due to editing.
> Draft of gutter decoration and guttermousedown event.

- EMBEDDING.md
- example/example.coffee
- src/coffee.coffee
- src/javascript.coffee
- test/cstest.html
- test/jstest.html
For example, to recognize a *.toString method on any object,
register a known function as '*.toString'.  The other wildcard
is '?.foo', which matches either 'x.foo()' or top-level 'foo().
> Support wildcards for known method names.

- src/controller.coffee
- test/coffee/tests.coffee
* `getReadOnly` and `setReadOnly` implemented, matching the Ace API (and calling down into Ace for `setReadOnly`)
* `@readOnly` is checked on the droplet side before hit testing, input focus, and key events. The droplet editor can still be scrolled, lines can be highlighted, but no modifications to the content of the document should be possible
* `setEditorState` didn't properly check `@paletteEnabled` and `@showPaletteInTextMode` to position the palette off-screen when necessary. That code only existed in the async `performMeltAnimation` and `performFreezeAnimation`. It now works either way.
* `enablePaletteAtStart` mostly worked if `false` was passed in, but there was a bug in that the palette was never moved off-screen. Solved by always calling `setEditorState` in the constructor.
* …
> add readOnly, textModeAtStart, fix enablePaletteAtStart & setEditorState

- EMBEDDING.md
- src/controller.coffee
In Applab we'd like to be able to have dropdowns with an "Upload new..." option that opens a modal dialog.  This PR lets dropdown options specify a click handler to be called instead of the default handler.
Sample usage:
```javascript
{display: 'Upload new...', click: (callback) -> promptImage(callback)}
```
The provided handler receives a callback which it can call to populate the socket value (usually after another user interaction).
> Allow dropdown options to specify their own `click` handler

- src/javascript.coffee
- test/jstest.html
Precedences for LogicalExpressions and to some degree UnaryExpressions were formerly not assigned the same way they were for BinaryExpressions; this PR fixes precedences assignments.
> LogicalExpressions precedence fix

- src/javascript.coffee
- test/jstest.html
For editing convenience, no longer make a block for values like `-1` or `+foo`.
> Don't make blocks for unary operators on literal values

- src/languages/javascript.coffee
Special-case the third socket of a for loop to accept certain kinds of statement-like blocks like `a += 1`. Note that true "statements" (like `break` or `var a =` statements) still cannot and should not be able to be dropped into the third socket.
> Allow command expression drops into third socket of for loop

- src/controller.coffee
I think that the copy-paste bug some people are seeing has to do with the cursor being in the wrong position when we do a paste. This PR will force the cursor into the correct position before a paste is done.
> Attempt to fix copy-paste error by forcing cursor into correct position

- Gruntfile.coffee
- css/droplet.css
- example/example.coffee
- src/controller.coffee
Add methods to Droplet to mimic Ace editor gutter decoration functionality. Changes from existing behavior:
- Droplet now has `setBreakpoint`, `clearBreakpoint`, `clearBreakpoints`, `getBreakpoints`, and `setAnnotations`, with behavior identical to Ace. Droplet will set all of these for itself when called and will also set them in its corresponding Ace editor.
- Droplet's `guttermousemove` now also fires when Ace's fires
- Droplet annotation texts can be read with a title-text
- Droplet line numbers are now on top and can recieve mouseover events directly
- Droplet annotation glyphs are centered vertically on lines
> Gutter compat

- package.json
- src/controller.coffee
- test/src/uitest.coffee
- test/uitest.html
Change to `controller.coffee` to abort a drag if the user is hovering over the grayed-out block that represents the place they picked up the block. I don't know if this is a good UI decision -- thoughts?
> Allow users to abort drags by replacing the block where they found it

- src/controller.coffee
When we drag a block to the front of a line, we should add a new line + indentation to the end of the block.
> add newline when drag/dropping block at front of line

- css/droplet.css
- src/controller.coffee
Two changes to the way the dropdown is shown:
- Added 17 pixels of padding to the right and changed to `scroll:auto`. We had previously not done this because the scrollbar could sometimes cover up some text.
- Set `min-width` to the size of the text input the dropdown is attached to, and update this when the width changes.
> Dropdown visuals: scroll auto and min-width to socket

- EMBEDDING.md
- Gruntfile.coffee
- example/example.html
- src/controller.coffee
- src/model.coffee
- src/parser.coffee
In `modeOptions`, embedders can now specify
```
dropdown: {
"0": {
exclusive: true,
options: ["hello"]
}
}
```
The change is backwards-compatible.
> Support for non-editable dropdown sockets

- src/languages/javascript.coffee
- test/src/jstest.coffee
Embedders can now specify beginner mode with a flag in the "categories" option:
```javascript
//...
modeOptions: {
categories: {
loops: {
color: "green",
beginner: true
}
}
}
//...
```
This will make for loops of this form mark only "b":
```javascript
for (var i = 0; i < b; i++) {
//...
}
```
It is currently very picky about which loops it chooses to do this with; they must be exactly of the form `(/*var*/ a = x; a < b; a++)` and `a` must be the same identifier in all three expressions.
> Beginner mode for "for" loops

- README.md
- src/controller.coffee
- src/model.coffee
- src/parser.coffee
Implements an extra parameter `next` in drop callback which gives information about the immediately next block, if it exists.
Can be used to ensure droppability of a block only before certain types of blocks.
> Extra parameter 'next' in drop callback

- css/droplet.css
- src/controller.coffee
Previously these two controller members referred to the same
element.  Now they are different, one nested in the other.
Now paletteWrapper deals with the sizing of the overall palette pane
but not the clipping or the containing, and paletteElement contains
all the children and does the clipping.  This allows embedders
such as Pencil Code to decorate the palette pane by attaching elements
to paletteWrapper (such as mode- or palette-switching buttons and menus)
without interfering with the working of the palette.
This is a no-op for most users of pencil code.
> Separate paletteWrapper and paletteElement.

- src/languages/coffee.coffee
- src/languages/javascript.coffee
- src/parser.coffee
Allow comment blocks to be dropped in indent contexts, and don't add parentheses or semicolons to them.
> Add classes and droppability for comment blocks

- src/controller.coffee
- test/test.html
Resize/reposition the main canvas when the gutter resizes to avoid this overlapping issue:
> Gutter resize fix

- README.md
Removes `accepts` from `addSocket` in README.md since the feature has been removed from droplet.
> Remove 'accepts' from README

- src/languages/coffee.coffee
This change allows coffeescript to recover from unescaped quotes entered in a socket.
If you enter `'What's up'` in a coffeescript socket, that string will misparse, but it will be caught as having quote characters on the edges, and it will be transformed into a correctly-escaped string by the parsing recovery logic.
> Simple recovery from coffee quoting errors in a socket.

- src/controller.coffee
- src/draw.coffee
`Editor.getLineBoundingBox(row)` where `row` is 0-indexed will return an instance of Droplet's `draw.Rectangle`, which has properties `x`, `y` ,`width`, `height` and methods `right()` and `bottom()`.
> Add line bounding box API

- Gruntfile.coffee
- src/controller.coffee
- src/model.coffee
- test/src/uitest.coffee
A new remember-socket PR to work with multiple documents. This will track the location of a socket through all (I think) operations except setValue.
> Remember socket floating

- src/languages/html.coffee
- test/src/htmltest.coffee
Assign colours to nodes based on the category and the node colour support is much wider.
The colour of the nodes with make it easy for the children to remember what node belongs to which category.
> HTML colour fixes

- src/controller.coffee
This fixes an issue in PencilCode where the shortcut to run the current program (Command-Return, or Control-Return on Linux/Windows) would also inadvertently add a new blank text block. Shift-Return was already excluded from inserting a new block.
> Don't insert text blocks when Return is pressed if the Control or Command keys are held down

- src/controller.coffee
- src/languages/coffee.coffee
- src/languages/javascript.coffee
- src/parser.coffee
- test/src/uitest.coffee
Brings back and adds a test for the feature where by default Droplet does not select the quotes in a quoted string (or, now, regexes)
> Refactor default text selection range into modes for string assistance

- src/languages/coffee.coffee
- src/model.coffee
- test/src/uitest.coffee
Fixes a feature that has been broken for a while or may never have worked, where in CoffeeScript mode if students write a quote inside a string it will automatically escape it. Adds a test for this feature as well.
> Fix string autoescape and add test

- src/controller.coffee
Fixes a bug where, previously, a +/- button on a block that was not the first in its indent or document would cause Droplet to break.
> Fix newline removal bug with +/- buttons

- src/languages/coffee.coffee
- src/languages/javascript.coffee
- src/view.coffee
- test/src/cstest.coffee
- test/src/jstest.coffee
This affects JavaScript and CoffeeScript mode. This will not be done in JavaScript if there are intervening comments or line breaks between the function variable and parentheses.
> Add a socket when there are no params in a function call

- src/controller.coffee
Prior to this change, socket reparse would modify the `updates` array of locations, but not restore the original values if the parent fails to parse with the new socket value. This would cause `Container#getFromLocation` to throw after falling off the end of the linked list.
The fix is to save the update locations before attempting to parse the socket as a new block, and restore them if the parent reparse fails.
This is a better fix for the JavaScript function sockets bug than https://github.com/droplet-editor/droplet/pull/130, which only treats the symptom but not the root cause.
> Restore update locations when a socket reparse fails

- src/controller.coffee
Cut and paste could get the editor into a bad state because `pressedVKey` wasn't always being cleared. Pressing `cmd+v` then `cmd+x` would hit the paste code path and throw.
> Fix cmd+x having `pressedVKey = true`

- Gruntfile.coffee
With `grunt build uglify` droplet-full.min.js is ~1.57 mb.
With `LANGUAGE=javascript grunt build uglify` droplet-full.min.js is ~0.31 mb (1/5 the size).
This is important during Hour of Code where every byte across the wire counts!
> Enable custom builds with only one language

- src/languages/javascript.coffee
Commit https://github.com/droplet-editor/droplet/commit/62b40fb727cd5a938fb49342b19c7136660decf7 added a click-target for user-defined functions with no parameters, so new params could be added in block mode.  Commit https://github.com/droplet-editor/droplet/commit/bb283afba434d38aee0201f420b72cfc939fa6d6 made that option configurable, but seems to have changed the default behavior to `false`.
This change re-enables adding params to user-definied functions with no params. It also updates function calls to also respect the `@opts.lockZeroParamFunctions` flag.
The default value of the modified flag is `false`, which doesn't lock zero-parameter functions (new parameters may be added by clicking inside the parentheses).
> Unify `@opts.zeroParamFunctions` behavior

- src/controller.coffee
Fixes #104.  Bind events separately for `.droplet-palette-header` and `.droplet-palette-scroller-stuffing` so clicking the palette scrollbar doesn't trigger the callback.
> Clicking the palette scrollbar shouldn't trigger a mousedown event

- src/controller.coffee
Reverts droplet-editor/droplet#135 due to a regression in IE10.  Blocks couldn't be dragged out from the toolbox because the `.palette-scroller-stuffing` didn't receive mouse events.
> Revert "Clicking the palette scrollbar shouldn't trigger a mousedown event"

- package.json
We started seeing the following failures on newer versions of patch5
```
Testing test/htmltest.html F
>> global failure
>> Message: TypeError: 'undefined' is not a constructor (evaluating 'new parse5.Parser(null, {
>>   decodeHtmlEntities: false,
>>   locationInfo: true
>> })')
>> Actual: null
>> Expected: undefined
>> file:///Users/brent/git/droplet/test/js/htmltest.js:16105
Testing test/jstest.html .......OK
Testing test/test.html F
>> global failure
>> Message: TypeError: 'undefined' is not a constructor (evaluating 'new parse5.Parser(null, {
>>   decodeHtmlEntities: false,
>>   locationInfo: true
>> })')
>> Actual: null
>> Expected: undefined
>> file:///Users/brent/git/droplet/test/js/tests.js:150972
Testing test/uitest.html F
>> global failure
>> Message: TypeError: 'undefined' is …
```
> Restrict version of patch5 as newer versions break tests

- src/languages/javascript.coffee
Incorrect JS was generated when pressing the '+' button on an else statement with no space before the bracket.
Before: `else{` -> `els if (__) e{`
After: `else{` -> `else if {`
The incorrect JS would fail to parse, throwing an error in acorn.js.  To the end-user it would appear as if the '+' button had no effect.
This bug was hidden for else statements with a space because `elseLocation` could be moved back one character (across the space) and still not impact the 'else' token.  The bug is only triggered when the space is missing.  Both tokens are trimmed after splitting so there is no change in the generated output.
> Fix off-by-one bug in the if/else add-button

- src/languages/javascript.coffee
This bug fix is for when the 'beginner' config option is set.  Without this change the following JS throws a parser error when switching from text to block mode:
```javascript
var items = [4, 5, 6];
for (var i = 0; i < items.length; i++) {
//
}
```
This is because the beginner for loop doesn't expect a nested block inside the test condition.
I've updated `isStandardForLoop` to also check that the right-side test is a Literal or Identifier.  If it's not, Droplet falls back to parsing the node as a non-beginner for loop.
---
Beginner for loop:
Non-beginner for loop:
> Ensure simple for loops don't have a block in node.test.right socket

- src/model.coffee
Before this change it returned the `DocumentStartToken`.  This ensures that calling `Editor::markBlock` with location `{row: 0, col: 0}` does mark the first block.
> Calling `getFromTextLocation` at location 0 should return a block

- src/model.coffee
Feedback from @dabbler0: `@start` is always a `DocumentStartToken`. (See https://github.com/droplet-editor/droplet/pull/143)
> Amend https://github.com/droplet-editor/droplet/pull/143

- src/languages/javascript.coffee
- test/src/jstest.coffee
Parentheses were being added when editing sockets on either side of an `AssignmentExpression`. However, the right side of the `VariableDeclarator` used `NEVER_PAREN`. So `x = __;` behaved differently from `var x = __;`
Changed `AssignmentExpression` to use `NEVER_PAREN` to match.
> add NEVER_PAREN to both sides of AssignmentExpression

- src/controller.coffee
There were a few places where Droplet redraws more than it needs to.  These changes are part of the focus-socket-on-mouseup changes.  Moving them to a separate PR to merge them early.
> Limit scope of redraws for highlights and cursors

- package.json
Version 1.0.1 has a breaking change for npm 0.10, but 1.0.0 works.
> Lock grunt-contrib-connect to the last version that supports npm 0.10

- src/controller.coffee
This fixes dragging `if` blocks into `for` loops, but there may be other instances of this bug.  Root cause is that `window.event` is undefined in Firefox.  In other browsers it's the event currently being handled.
> Firefox doesn't have a global event object

- src/controller.coffee
Prior to https://github.com/droplet-editor/droplet/pull/150 the redraw was triggered indirectly via `mousedown -> clearLassoSelection() -> redrawHighlights() -> redrawMain()`.
This fixes the bug where pressing the '+' button on an `if` block appears to have no effect until something else happens to trigger a `redrawMain()`.
> Redraw when an add- or subtract-button click is handled

- src/controller.coffee
* We want to allow certain levels in our curriculum to start up droplet with the palette group as something other than the default group (which is currently always the first one).
* Allow the supplied `@paletteGroups` object to optionally specify an `id` for each group. When present, it will be used to generate a DOM id for the group header (e.g. if `math` is the id, the header DOM id will be `droplet-palette-group-header-math`). This is useful for assigning tooltips to the header elements.
* Exposed a new `changePaletteGroup(group)` method and changed the existing code to use that method. The `group` parameter will be used to match from the `@paletteGroups` array - it can match the group object itself, the `name`, or the `id` of the group.
* The `@paletteGroups` object (supplied at …
> expose changePaletteGroup method, allow groups to have ids

- package.json
- src/controller.coffee
- src/languages/coffee.coffee
- src/languages/html.coffee
- src/languages/javascript.coffee
- src/parser.coffee
- src/treewalk.coffee
* Change `constructHandwrittenBlock` in the `isComment` case to call a new `indentAndCommentMarker` function, to handle single-line comments such that the comment marker is outside of the socket (and therefore, can't be deleted)
* Changed how the `ENTER_KEY` is handled when inside a socket in a comment: Previously, nothing happened. Now, a new single-line comment is created on the next line with the focus in the new socket so that typing can continue.
* Fixed some issues with how handwritten blocks are constructed by properly parenting the `TextToken` and `Socket` that belong to the new block.
* Fixed an issue where `@setCursor` would cause comments to be reparsed - and blank comments would fail to parse
_NOTE: multi-line comments still have issues and this PR does not address those …
> Single-line comment changes

- src/controller.coffee
- src/languages/javascript.coffee
* Allow a known function that is considered `known.anyobj` (starting with `*.`) to specify an `objectDropdown` - which is essentially the same as a parameter dropdown, but instead applies to the `callee.object` (the left side of the `MemberExpression`)
* A little known feature allows you to specify `dropdownOnly` inside your dropdown object, which makes the socket non-editable. Unfortunately, the dropdown couldn't change the socket text in this case as well, so I fixed that.
* PR feedback from last PR (https://github.com/droplet-editor/droplet/pull/160): use CoffeeScript existential operator
> allow objectDropdown in known.anyobj, allow changing socket in dropdownOnly mode

- src/languages/javascript.coffee
- test/src/jstest.coffee
Re-opening PR https://github.com/droplet-editor/droplet/pull/168 against the correct branch.
---
Prior to this change, a socket reparse of `{a: 1}` would create a `LabeledStatement` node instead of `ObjectExpression`.
`LabeledStatement` is an unrecognized node, so `Editor::reparse` doesn't set the correct cursor location.  Subsequent calls to `getCursor`/`setCursor` throw an exception.  To the user it appears the editor is frozen.
This change wraps the program text with parentheses if the text starts with '{'.  Chrome fixed a similar issue in the Dev Tools console (https://bugs.chromium.org/p/chromium/issues/detail?id=499864), however they also check that the text ends with '}'.
> Allow parsing of bare JavaScript ObjectExpression

- css/droplet.css
- src/controller.coffee
- src/model.coffee
- src/parser.coffee
- src/treewalk.coffee
Add a parseContext property to the Document class, so that floating blocks can know what can be dropped in them instead of thinking they are the root context. Also generalizes some C-specific magic strings from treewalker.
> Parse contexts for documents

- src/controller.coffee
- test/src/uitest.coffee
Formerly, Droplet's undo and rememberedSocket data would become corrupted if you deleted a floatingBlock that was not on the top of the floatingBlock stack. This would cause all the document indices to shift, but the undo stack wouldn't shift with them. This adds that pass to fix the bug, along with a test.
> Make test for bug with undo and rememberedSocket document indices

- src/languages/c.coffee
- src/treewalk.coffee
- test/src/ctest.coffee
Add or remove semicolons as necessary when dropping expressionStatement blocks into blockItem contexts or vice versa.
> Semicolon adaptation
